Test acap signing
Change-Id: I7c3f8f1467e72ec577747cb27e9f738b051b8155

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -47,7 +47,7 @@ jobs:
     steps:
       - name: Checkout repo
         # sha for actions/checkout@v3 at time of commit.
-        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
+        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
       - name: Create test image metadata
         id: meta_test
         uses: ./.github/actions/metadata-action
@@ -108,10 +108,16 @@ jobs:
     strategy:
       matrix:
         arch: [armv7hf, aarch64]
+    outputs:
+      TAG: ${{ steps.vars.outputs.TAG }}
+      EAP_FILE: ${{ steps.get_artifact.outputs.EAP_FILE }}
     steps:
+      - name: Set output
+        id: vars
+        run: echo "TAG=${GITHUB_REF#refs/*/}" >> ${GITHUB_OUTPUT}
       - name: Checkout repo
         # sha for actions/checkout@v3 at time of commit.
-        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
+        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
       - name: Create base image metadata
         id: meta
         uses: ./.github/actions/metadata-action
@@ -139,25 +145,33 @@ jobs:
       - name: Get EAP from base image
         id: get_artifact
         run: |
-          echo "Full_name ${{ steps.meta.outputs.full_name }}"
-
           docker cp $(docker create "${{ steps.meta.outputs.full_name }}"):/opt/app .build
           export EAP_FILE=$(find .build -type f -name "*.eap" -printf "%f\n")
           delimiter="$(openssl rand -hex 8)"
-          echo "EAP_FILE<<${delimiter}" >> ${GITHUB_ENV}
-          echo "${EAP_FILE}" >> ${GITHUB_ENV}
-          echo "${delimiter}" >> ${GITHUB_ENV}
-          echo "EAP_FILE ${EAP_FILE}"
+          echo "EAP_FILE<<${delimiter}" >> ${GITHUB_OUTPUT}
+          echo "${EAP_FILE}" >> ${GITHUB_OUTPUT}
+          echo "${delimiter}" >> ${GITHUB_OUTPUT}
       - name: Sign eap-file
         run: |
           cd .build
           curl -XPOST -H 'accept: */*' -H 'Content-Type: multipart/form-data' -H 'Authorization: Bearer ${{secrets.ACAP_PORTAL_SIGNING_BEARER_TOKEN}}' \
-          'https://gw.ext.csi-api.axis.com/ext/acap/admin/application/${{secrets.ACAP_PORTAL_SIGNING_ID}}/sign/binary' -F uploadedFile=@"${{ env.EAP_FILE }}" --output Signed_${{ env.EAP_FILE }}
+          'https://gw.ext.csi-api.axis.com/ext/acap/admin/application/${{secrets.ACAP_PORTAL_SIGNING_ID}}/sign/binary' -F uploadedFile=@"${{ steps.build_and_push.outputs.EAP_FILE }}" --output Signed_${{ steps.build_and_push.outputs.EAP_FILE }}
       - name: Upload artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
         with:
-          name: signed-artifact-${{ matrix.arch }}
-          path: .build/Signed_${{ env.EAP_FILE }}
+          name: Signed_${{ steps.build_and_push.outputs.EAP_FILE }}
+          path: .build/Signed_${{ steps.build_and_push.outputs.EAP_FILE }}
+      - name: Save file name
+        run: |
+          if [ ${{ matrix.arch }} = armv7hf ]
+          then
+            echo "EAP_FILE_ARMV7HF=Signed_${{ steps.build_and_push.outputs.EAP_FILE }}" >> $GITHUB_ENV
+          elif [ ${{ matrix.arch }} = aarch64 ]
+          then
+            echo "EAP_FILE_AARCH64=Signed_${{ steps.build_and_push.outputs.EAP_FILE }}" >> $GITHUB_ENV
+          else
+            echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
+          fi
       - name: Create containerized image metadata
         id: meta_containerized
         uses: ./.github/actions/metadata-action
@@ -177,3 +191,88 @@ jobs:
           use_qemu: 'true'
           registry_user: ${{ secrets.ECOSYSTEM_SERVICE_USER_DOCKER_HUB }}
           registry_token: ${{ secrets.ECOSYSTEM_ACCESS_TOKEN_DOCKER_HUB }}
+
+  create_prerelease:
+    permissions: write-all
+    runs-on: ubuntu-latest
+    needs: build_and_push
+    outputs:
+      RELEASE_ID: ${{ steps.prerelease.outputs.RELEASE_ID }}
+    env:
+      TAG: ${{ needs.build_and_push.outputs.TAG }}
+    steps:
+    - name: Create prerelease
+      id: prerelease
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        export RELEASE_ID=$( jq -r '.id' <<< $(
+        gh api \
+        --method POST \
+        -H "Accept: application/vnd.github+json" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        /repos/kristinub/test_acap_sdk/releases \
+        -f tag_name='${{ env.TAG }}' \
+        -f target_commitish='main' \
+        -f name='${{ env.TAG }}' \
+        -f body='Prerelease for ${{ env.TAG }}' \
+        -F draft=false \
+        -F prerelease=true \
+        -F generate_release_notes=false
+          ))
+        delimiter="$(openssl rand -hex 8)"
+        echo "RELEASE_ID<<${delimiter}" >> ${GITHUB_OUTPUT}
+        echo "${RELEASE_ID}" >> ${GITHUB_OUTPUT}
+        echo "${delimiter}" >> ${GITHUB_OUTPUT}
+        echo "RELEASE_ID ${RELEASE_ID}"
+
+  download-and-upload-artifacts:
+    permissions: write-all
+    runs-on: ubuntu-latest
+    needs: [create_prerelease, build_and_push]
+    strategy:
+      matrix:
+        arch: [armv7hf, aarch64]
+    env:
+      RELEASE_ID: ${{ needs.create_prerelease.outputs.RELEASE_ID }}
+      EAP_FILE: ${{ needs.build_and_push.outputs.EAP_FILE }}
+    steps:
+    - name: Get EAP file name
+      run: |
+        if [ ${{ matrix.arch }} = armv7hf ]
+        then
+          echo "EAP_FILE=${{ env.EAP_FILE_ARMV7HF }}" >> $GITHUB_ENV
+        elif [ ${{ matrix.arch }} = aarch64 ]
+        then
+          echo "EAP_FILE=${{ env.EAP_FILE_AARCH64 }}" >> $GITHUB_ENV
+        else
+          echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
+        fi
+    - name: Download artifacts
+      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
+      with:
+        name: ${{ env.EAP_FILE }}
+        path: ./
+    - name: Upload file to GitHub release
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github.manifold-preview" \
+          -H "Content-Type: application/zip" \
+          --data-binary @${{ env.EAP_FILE }} \
+          "https://uploads.github.com/repos/kristinuub/test_acap_sdk/releases/${{env.RELEASE_ID}}/assets?name=${{ env.EAP_FILE }}" \
+          -w "%{http_code}\n" -o /dev/null)
+        echo "HTTP_RESPONSE=$RESPONSE" >> $GITHUB_ENV
+    - name: Check that asset has been uploaded correctly
+      run: |
+        if [[ -n "$HTTP_RESPONSE" && "$HTTP_RESPONSE" =~ ^[0-9]+$ ]]; then
+          if [ "$HTTP_RESPONSE" -eq 201 ]; then
+            echo "HTTP response code is 201, upload was succesful"
+          else
+            echo "HTTP response code is: $HTTP_RESPONSE, upload was not succesful"
+            exit 1
+          fi
+        else
+          echo "HTTP_RESPONSE is empty or not a valid integer: $HTTP_RESPONSE"
+        fi
