Acap signing  (#48)
Added automatic signing of the ACAP Runtime application.
When a new tag is created the application will be signed and uploaded to artifacts. A prerelease is created and the artifacts uploaded as assets.

---------

Co-authored-by: Kristin Unger Berglund <kristinu@axis.com>

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -46,15 +46,15 @@ jobs:
     steps:
       - name: Checkout repo
         # sha for actions/checkout@v3 at time of commit.
-        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
+        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
       - name: Create test image metadata
         id: meta_test
         uses: ./.github/actions/metadata-action
         with:
           suffix: -${{ matrix.arch }}-test
           repository: ${{ env.DOCKER_HUB_REPOSITORY }}
-          latest: 'false'
-          get_version: 'true'
+          latest: "false"
+          get_version: "true"
       - name: Update manifest file
         if: ( github.ref_type == 'tag')
         uses: ./.github/actions/update-acap-manifest-action
@@ -107,17 +107,20 @@ jobs:
     strategy:
       matrix:
         arch: [armv7hf, aarch64]
+    outputs:
+      EAP_FILE_ARMV7HF: ${{ steps.save_full_file_name.outputs.EAP_FILE_ARMV7HF }}
+      EAP_FILE_AARCH64: ${{ steps.save_full_file_name.outputs.EAP_FILE_AARCH64 }}
     steps:
       - name: Checkout repo
         # sha for actions/checkout@v3 at time of commit.
-        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
+        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
       - name: Create base image metadata
         id: meta
         uses: ./.github/actions/metadata-action
         with:
           suffix: -${{ matrix.arch }}
           repository: ${{ env.DOCKER_HUB_REPOSITORY }}
-          get_version: 'true'
+          get_version: "true"
       - name: Update manifest file
         if: ( github.ref_type == 'tag')
         uses: ./.github/actions/update-acap-manifest-action
@@ -131,9 +134,58 @@ jobs:
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           target: runtime-base
-          push: true
-          registry_user: ${{ secrets.ECOSYSTEM_SERVICE_USER_DOCKER_HUB }}
-          registry_token: ${{ secrets.ECOSYSTEM_ACCESS_TOKEN_DOCKER_HUB }}
+          push: false
+          load: true
+      - name: Set name of EAP-file
+        id: get_eap_file_name
+        run: |
+          docker cp $(docker create "${{ steps.meta.outputs.full_name }}"):/opt/app .build
+          export EAP_FILE=$(find .build -type f -name "*.eap" -printf "%f\n")
+          delimiter="$(openssl rand -hex 8)"
+          echo "EAP_FILE<<${delimiter}" >> ${GITHUB_ENV}
+          echo "${EAP_FILE}" >> ${GITHUB_ENV}
+          echo "${delimiter}" >> ${GITHUB_ENV}
+      - name: Refactor naming of EAP-file for signed output
+        run: |
+          signed_output=$(echo "${{ env.EAP_FILE }}" | sed 's/\.eap/_signed.eap/')
+          echo "SIGNED_EAP_FILE=${signed_output}" >> $GITHUB_ENV
+      - name: Sign eap-file
+        run: |
+          cd .build
+          RESPONSE=$(curl -XPOST -H 'accept: */*' -H 'Content-Type: multipart/form-data' -H 'Authorization: Bearer ${{secrets.ACAP_PORTAL_SIGNING_BEARER_TOKEN}}' \
+          '${{ vars.ACAP_PORTAL_URL }}/${{secrets.ACAP_PORTAL_SIGNING_ID}}/sign/binary' -F uploadedFile=@"${{ env.EAP_FILE }}" --output ${{ env.SIGNED_EAP_FILE }} \
+          -w "%{http_code}\n" -o /dev/null)
+          echo "HTTP_RESPONSE=$RESPONSE" >> $GITHUB_ENV
+      - name: Check that acap has been signed
+        run: |
+          if [[ -n "$HTTP_RESPONSE" && "$HTTP_RESPONSE" =~ ^[0-9]+$ ]]; then
+            if [ "$HTTP_RESPONSE" -eq 200 ]; then
+              echo "HTTP response code is 200, signing was succesful"
+            else
+              echo "HTTP response code is: $HTTP_RESPONSE, signing was not succesful"
+              exit 1
+            fi
+          else
+            echo "HTTP_RESPONSE is empty or not a valid integer: $HTTP_RESPONSE"
+          fi
+      - name: Upload artifact
+        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
+        with:
+          name: ${{ env.SIGNED_EAP_FILE }}
+          path: .build/${{ env.SIGNED_EAP_FILE }}
+          if-no-files-found: error
+      - name: Save file name
+        id: save_full_file_name
+        run: |
+          if [ ${{ matrix.arch }} = armv7hf ]
+          then
+            echo "EAP_FILE_ARMV7HF=${{ env.SIGNED_EAP_FILE }}" >> $GITHUB_OUTPUT
+          elif [ ${{ matrix.arch }} = aarch64 ]
+          then
+            echo "EAP_FILE_AARCH64=${{ env.SIGNED_EAP_FILE }}" >> $GITHUB_OUTPUT
+          else
+            echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
+          fi
       - name: Create containerized image metadata
         id: meta_containerized
         uses: ./.github/actions/metadata-action
@@ -148,8 +200,96 @@ jobs:
           labels: ${{ steps.meta_containerized.outputs.labels }}
           push: true
           build-args: |
-              ARCH=${{ matrix.arch }}
-              RUNTIME_VERSION=${{ steps.meta.outputs.version }}
-          use_qemu: 'true'
+            ARCH=${{ matrix.arch }}
+            RUNTIME_VERSION=${{ steps.meta.outputs.version }}
+          use_qemu: "true"
           registry_user: ${{ secrets.ECOSYSTEM_SERVICE_USER_DOCKER_HUB }}
           registry_token: ${{ secrets.ECOSYSTEM_ACCESS_TOKEN_DOCKER_HUB }}
+
+  create_prerelease:
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    needs: build_and_push
+    if: (github.event_name != 'pull_request')
+    outputs:
+      RELEASE_ID: ${{ steps.prerelease.outputs.RELEASE_ID }}
+    steps:
+      - name: Set TAG
+        id: vars
+        run: echo "TAG=${GITHUB_REF#refs/*/}" >> ${GITHUB_ENV}
+      - name: Create prerelease
+        uses: "actions/github-script@v6"
+        id: prerelease
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          script: |
+            try {
+              const response = await github.rest.repos.createRelease({
+                draft: false,
+                generate_release_notes: true,
+                name: '${{ env.TAG }}',
+                owner: context.repo.owner,
+                prerelease: true,
+                repo: context.repo.repo,
+                tag_name: '${{ env.TAG }}',
+              });
+              core.setOutput('RELEASE_ID', response.data.id);
+            } catch (error) {
+              core.setFailed(error.message);
+            }
+
+  download-and-upload-artifacts:
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    needs: [create_prerelease, build_and_push]
+    strategy:
+      matrix:
+        arch: [armv7hf, aarch64]
+    env:
+      RELEASE_ID: ${{ needs.create_prerelease.outputs.RELEASE_ID }}
+      EAP_FILE_AARCH64: ${{ needs.build_and_push.outputs.EAP_FILE_AARCH64 }}
+      EAP_FILE_ARMV7HF: ${{ needs.build_and_push.outputs.EAP_FILE_ARMV7HF }}
+    steps:
+      - name: Get EAP file name
+        id: full_eap_name
+        run: |
+          if [ ${{ matrix.arch }} = armv7hf ]
+          then
+            echo "EAP_FILE=${{ needs.build_and_push.outputs.EAP_FILE_ARMV7HF }}" >> $GITHUB_ENV
+          elif [ ${{ matrix.arch }} = aarch64 ]
+          then
+            echo "EAP_FILE=${{ needs.build_and_push.outputs.EAP_FILE_AARCH64 }}" >> $GITHUB_ENV
+          else
+            echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
+          fi
+      - name: Download artifacts
+        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
+        with:
+          name: ${{ env.EAP_FILE }}
+          path: ./
+      - name: Upload file to GitHub release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.manifold-preview" \
+            -H "Content-Type: application/zip" \
+            --data-binary @${{ env.EAP_FILE }} \
+            "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/${{env.RELEASE_ID}}/assets?name=${{ env.EAP_FILE }}" \
+            -w "%{http_code}\n" -o /dev/null)
+          echo "HTTP_RESPONSE=$RESPONSE" >> $GITHUB_ENV
+      - name: Check that asset has been uploaded correctly
+        run: |
+          if [[ -n "$HTTP_RESPONSE" && "$HTTP_RESPONSE" =~ ^[0-9]+$ ]]; then
+            if [ "$HTTP_RESPONSE" -eq 201 ]; then
+              echo "HTTP response code is 201, upload was succesful"
+            else
+              echo "HTTP response code is: $HTTP_RESPONSE, upload was not succesful"
+              exit 1
+            fi
+          else
+            echo "HTTP_RESPONSE is empty or not a valid integer: $HTTP_RESPONSE"
+          fi
