Updates of workflows and actions (#69)

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,21 +7,21 @@ name: CI/CD workflow.
 on:
   push:
     branches:
-      - 'main'
+      - "main"
     tags:
       # semver, e.g. 1.2.0 (does not match 0.1.2)
-      - '[1-9]+.[0-9]+.[0-9]+'
+      - "[1-9]+.[0-9]+.[0-9]+"
       # semver with prerelease info, e.g. 1.0.2-beta.1 or 1.2.3-rc.10
-      - '[1-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
+      - "[1-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+"
       # do not match prerelease starting w/ 0, e.g. 1.0.2-beta.0 or 1.2.3-rc.01
-      - '![1-9]+.[0-9]+.[0-9]+-[a-z]+.[0]*'
+      - "![1-9]+.[0-9]+.[0-9]+-[a-z]+.[0]*"
       # semver with date info, e.g. 1.0.2-20221125
-      - '[1-9]+.[0-9]+.[0-9]+-[0-9]+'
+      - "[1-9]+.[0-9]+.[0-9]+-[0-9]+"
       # do not match date starting w/ 0, e.g. 1.0.2-01232023
-      - '![1-9]+.[0-9]+.[0-9]+-[0]*'
+      - "![1-9]+.[0-9]+.[0-9]+-[0]*"
   pull_request:
     branches:
-      - 'main'
+      - "main"
 
 jobs:
   # Build and run the test suite
@@ -94,8 +94,8 @@ jobs:
 
   # Build base image and extract eap file then use ACAP portal to sign it
   # This job is skipped if not on main branch or if build_and_test job has failed
-  build_and_sign_acap:
-    name: Build and sign acap
+  build:
+    name: Build acap
     runs-on: ubuntu-latest
     needs: build_and_test
     if: (github.event_name != 'pull_request')
@@ -105,9 +105,20 @@ jobs:
     outputs:
       EAP_FILE_ARMV7HF: ${{ steps.save_full_file_name.outputs.EAP_FILE_ARMV7HF }}
       EAP_FILE_AARCH64: ${{ steps.save_full_file_name.outputs.EAP_FILE_AARCH64 }}
+      SHORT_SHA: ${{ steps.save_full_file_name.outputs.SHORT_SHA }}
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
+      - name: get_short_sha
+        run: |
+          sha=${{ github.sha }}
+          strip_sha=${sha:0:7}
+          echo "SHORT_SHA=${strip_sha}" >> $GITHUB_ENV
+      - uses: actions/cache@v4
+        if: ${{ (github.ref_type == 'tag') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
+        with:
+          path: ${{ github.workspace }}/build-${{ matrix.arch }}
+          key: key-${{ env.SHORT_SHA }}-${{ github.run_id }}-${{ matrix.arch }}
       - name: Create base image metadata
         id: meta
         uses: ./.github/actions/metadata-action
@@ -115,12 +126,24 @@ jobs:
           suffix: -${{ matrix.arch }}
           repository: ${{ vars.REPOSITORY_DOCKER_HUB }}
           get_version: "true"
+      - name: Get changes for manifest
+        id: manifest-settings
+        if: ${{ (github.ref_type == 'tag') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
+        run: |
+          if [ ${{github.ref_type}} == tag ]; then
+              echo "version_value=${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT
+              echo "append_sha='false'" >> $GITHUB_OUTPUT
+          else
+              echo "version_value=-${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT
+              echo "append_sha='true'" >> $GITHUB_OUTPUT
+          fi
       - name: Update manifest file
         if: ( github.ref_type == 'tag')
         uses: ./.github/actions/update-acap-manifest-action
         with:
           manifest_file: ./manifest-${{ matrix.arch }}.json
-          value: ${{ steps.meta.outputs.version }}
+          append: ${{ steps.manifest-settings.outputs.append_sha}}
+          value: ${{ steps.manifest-settings.outputs.version_value }}
       - name: Build and push base image
         uses: ./.github/actions/docker-build-push-action
         with:
@@ -132,6 +155,7 @@ jobs:
           load: true
       - name: Set name of EAP-file
         id: get_eap_file_name
+        if: ${{ (github.ref_type == 'tag') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
         run: |
           docker cp $(docker create "${{ steps.meta.outputs.full_name }}"):/opt/app .build
           export EAP_FILE=$(find .build -type f -name "*.eap" -printf "%f\n")
@@ -139,6 +163,73 @@ jobs:
           echo "EAP_FILE<<${delimiter}" >> ${GITHUB_ENV}
           echo "${EAP_FILE}" >> ${GITHUB_ENV}
           echo "${delimiter}" >> ${GITHUB_ENV}
+      - name: Add sha to EAP-file name
+        if: ${{ (github.ref_type == 'tag') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
+        run: |
+          eap_file_w_sha=$(echo $"${{ env.EAP_FILE }}" | sed 's/\.eap/_${{ env.SHORT_SHA }}.eap/')
+          echo "EAP_FILE_W_SHA=${eap_file_w_sha}" >> $GITHUB_ENV
+          cp build/${{ env.EAP_FILE }} build/$eap_file_w_sha
+      - name: Save full file name
+        id: save_full_file_name
+        if: ${{ (github.ref_type == 'tag') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
+        run: |
+          echo "SHORT_SHA=${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT
+          if [ ${{ matrix.arch }} = armv7hf ]
+          then
+            echo "EAP_FILE_ARMV7HF=${{ env.EAP_FILE_W_SHA }}" >> $GITHUB_OUTPUT
+          elif [ ${{ matrix.arch }} = aarch64 ]
+          then
+            echo "EAP_FILE_AARCH64=${{ env.EAP_FILE_W_SHA }}" >> $GITHUB_OUTPUT
+          else
+            echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
+          fi
+      - name: Move EAP-file to cache location
+        if: ${{ (github.ref_type == 'tag') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
+        run: |
+          mkdir -p ${{ github.workspace }}/build-${{ matrix.arch }}
+          #rm -f ${{ github.workspace }}/build-${{ matrix.arch }}/${{ env.EAP_FILE_W_SHA }}
+          mv build/${{ env.EAP_FILE_W_SHA }} ${{ github.workspace }}/build-${{ matrix.arch }}/.
+
+  # Sign the eap-file from the build
+  sign-eap:
+    runs-on: ubuntu-latest
+    if: ${{ (github.ref_type == 'tag') || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
+    needs: build
+    permissions:
+      contents: write
+    strategy:
+      fail-fast: false
+      matrix:
+        arch: ["armv7hf", "aarch64"]
+      max-parallel: 1
+    env:
+      EAP_FILE_ARMV7HF: ${{ needs.build.outputs.EAP_FILE_ARMV7HF }}
+      EAP_FILE_AARCH64: ${{ needs.build.outputs.EAP_FILE_AARCH64 }}
+      SHORT_SHA: ${{ needs.build.outputs.SHORT_SHA }}
+    outputs:
+      EAP_FILE_SIGNED_ARMV7HF: ${{ steps.save_full_file_name.outputs.EAP_FILE_SIGNED_ARMV7HF }}
+      EAP_FILE_SIGNED_AARCH64: ${{ steps.save_full_file_name.outputs.EAP_FILE_SIGNED_AARCH64 }}
+    steps:
+      - name: Get EAP file name
+        id: full_eap_name
+        run: |
+          if [ ${{ matrix.arch }} = armv7hf ]
+          then
+              echo "EAP_FILE=${{ env.EAP_FILE_ARMV7HF }}" >> $GITHUB_ENV
+          elif [ ${{ matrix.arch }} = aarch64 ]
+          then
+              echo "EAP_FILE=${{ env.EAP_FILE_AARCH64 }}" >> $GITHUB_ENV
+          else
+              echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
+          fi
+      - uses: actions/cache/restore@v4
+        with:
+          path: ${{ github.workspace }}/build-${{ matrix.arch }}
+          key: key-${{ env.SHORT_SHA }}-${{ github.run_id }}-${{ matrix.arch }}
+      - name: Get cached EAP-file
+        run: |
+          mkdir -p build
+          mv ${{ github.workspace }}/build-${{ matrix.arch }}/${{ env.EAP_FILE }} build/.
       - name: Refactor naming of EAP-file for signed output
         run: |
           signed_output=$(echo "${{ env.EAP_FILE }}" | sed 's/\.eap/_signed.eap/')
@@ -146,9 +237,11 @@ jobs:
       - name: Sign eap-file
         run: |
           cd .build
-          RESPONSE=$(curl -XPOST -H 'accept: */*' -H 'Content-Type: multipart/form-data' -H 'Authorization: Bearer ${{secrets.ACAP_PORTAL_SIGNING_BEARER_TOKEN}}' \
-          '${{ vars.ACAP_PORTAL_URL }}/${{secrets.ACAP_PORTAL_SIGNING_ID}}/sign/binary' -F uploadedFile=@"${{ env.EAP_FILE }}" --output ${{ env.SIGNED_EAP_FILE }} \
-          -w "%{http_code}\n" -o /dev/null)
+          RESPONSE=$(curl -XPOST -H 'accept: */*' -H 'Content-Type: multipart/form-data' \
+          -H 'Authorization: Bearer ${{secrets.ACAP_PORTAL_SIGNING_BEARER_TOKEN}}' \
+          '${{ vars.ACAP_PORTAL_URL }}/${{secrets.ACAP_PORTAL_SIGNING_ID}}/sign/binary' \
+          -F uploadedFile=@"${{ env.EAP_FILE }}" --output ${{ env.SIGNED_EAP_FILE }} \
+          -w "%{http_code}\n" -o /dev/null --http1.1)
           echo "HTTP_RESPONSE=$RESPONSE" >> $GITHUB_ENV
       - name: Check that acap has been signed
         run: |
@@ -163,7 +256,7 @@ jobs:
             echo "HTTP_RESPONSE is empty or not a valid integer: $HTTP_RESPONSE"
           fi
       - name: Upload artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: ${{ env.SIGNED_EAP_FILE }}
           path: .build/${{ env.SIGNED_EAP_FILE }}
@@ -173,10 +266,10 @@ jobs:
         run: |
           if [ ${{ matrix.arch }} = armv7hf ]
           then
-            echo "EAP_FILE_ARMV7HF=${{ env.SIGNED_EAP_FILE }}" >> $GITHUB_OUTPUT
+            echo "EAP_FILE_SIGNED_ARMV7HF=${{ env.SIGNED_EAP_FILE }}" >> $GITHUB_OUTPUT
           elif [ ${{ matrix.arch }} = aarch64 ]
           then
-            echo "EAP_FILE_AARCH64=${{ env.SIGNED_EAP_FILE }}" >> $GITHUB_OUTPUT
+            echo "EAP_FILE_SIGNED_AARCH64=${{ env.SIGNED_EAP_FILE }}" >> $GITHUB_OUTPUT
           else
             echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
           fi
@@ -187,7 +280,7 @@ jobs:
   build_containerized:
     name: Build and push containerized images
     runs-on: ubuntu-latest
-    needs: build_and_test
+    needs: [build_and_test, build]
     if: (github.event_name != 'pull_request')
     strategy:
       matrix:
@@ -226,11 +319,11 @@ jobs:
   # This job is skipped if not a tag or if the build_and_sign_acap and
   # build_containerized jobs have not completed successfully.
   create_prerelease:
+    if: (github.ref_type == 'tag')
     permissions:
       contents: write
     runs-on: ubuntu-latest
-    needs: [build_and_sign_acap, build_containerized]
-    if: (github.ref_type == 'tag')
+    needs: [build, sign-eap, build_containerized]
     outputs:
       RELEASE_ID: ${{ steps.prerelease.outputs.RELEASE_ID }}
     steps:
@@ -263,32 +356,33 @@ jobs:
   # This job is skipped if create_prerelease or build_and_sign_acap jobs have
   # not completed successfully.
   download-and-upload-artifacts:
+    if: (github.ref_type == 'tag')
     permissions:
       contents: write
     runs-on: ubuntu-latest
-    needs: [create_prerelease, build_and_sign_acap]
+    needs: [create_prerelease, build, sign-eap]
     strategy:
       matrix:
         arch: [armv7hf, aarch64]
     env:
       RELEASE_ID: ${{ needs.create_prerelease.outputs.RELEASE_ID }}
-      EAP_FILE_AARCH64: ${{ needs.build_and_sign_acap.outputs.EAP_FILE_AARCH64 }}
-      EAP_FILE_ARMV7HF: ${{ needs.build_and_sign_acap.outputs.EAP_FILE_ARMV7HF }}
+      EAP_FILE_SIGNED_ARMV7HF: ${{ needs.sign-eap.outputs.EAP_FILE_SIGNED_ARMV7HF }}
+      EAP_FILE_SIGNED_AARCH64: ${{ needs.sign-eap.outputs.EAP_FILE_SIGNED_AARCH64 }}
     steps:
       - name: Get EAP file name
         id: full_eap_name
         run: |
           if [ ${{ matrix.arch }} = armv7hf ]
           then
-            echo "EAP_FILE=${{ needs.build_and_sign_acap.outputs.EAP_FILE_ARMV7HF }}" >> $GITHUB_ENV
+            echo "EAP_FILE=${{ env.EAP_FILE_SIGNED_ARMV7HF }}" >> $GITHUB_ENV
           elif [ ${{ matrix.arch }} = aarch64 ]
           then
-            echo "EAP_FILE=${{ needs.build_and_sign_acap.outputs.EAP_FILE_AARCH64 }}" >> $GITHUB_ENV
+            echo "EAP_FILE=${{ env.EAP_FILE_SIGNED_AARCH64 }}" >> $GITHUB_ENV
           else
             echo "::error::Non valid architecture '${{ matrix.arch }}' encountered"
           fi
       - name: Download artifacts
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: ${{ env.EAP_FILE }}
           path: ./
