correct docker hub creds

diff --git a/.github/workflows/docker_build_push.yml b/.github/workflows/docker_build_push.yml
--- a/.github/workflows/docker_build_push.yml
+++ b/.github/workflows/docker_build_push.yml
@@ -16,7 +16,9 @@ on:
 
 # Environment variables that are valid for all jobs
 env:
-  DOCKERHUB_REPOSITORY: 'axisecp/acap-runtime'
+  DOCKER_HUB_REPOSITORY: 'axisecp/acap-runtime'
+  DOCKER_HUB_USER: ${{ secrets.ECOSYSTEM_SERVICE_USER_DOCKER_HUB }}
+  DOCKER_HUB_TOKEN: ${{ secrets.ECOSYSTEM_ACCESS_TOKEN_DOCKER_HUB }}
 
 jobs:
   # Build and run the test suite
@@ -42,7 +44,7 @@ jobs:
         uses: ./.github/actions/metadata-action
         with:
           suffix: -${{ matrix.arch }}-test
-          repository: ${{ env.DOCKERHUB_REPOSITORY }}
+          repository: ${{ env.DOCKER_HUB_REPOSITORY }}
           latest: 'false'
       - name: Build test image
         uses: ./.github/actions/docker-build-push-action
@@ -53,79 +55,79 @@ jobs:
           push: false
           load: true
           build-args: TEST=true
-      # - name: Set environment variables for test
-      #   shell: bash
-      #   run: |
-      #     if [ ${{ matrix.arch }} = armv7hf ]
-      #     then
-      #       echo "AXIS_TARGET_ADDR=${{ env.AXIS_TARGET_ADDR_ARMV7HF }}" >> $GITHUB_ENV
-      #     else
-      #       echo "AXIS_TARGET_ADDR=${{ env.AXIS_TARGET_ADDR_AARCH64 }}" >> $GITHUB_ENV
-      #     fi
-      #     echo "ACAP_DOCKER_IMAGE_NAME=${{ steps.meta_test.outputs.tags }}" >> $GITHUB_ENV
-      # - name: Run the test image
-      #   uses: ./.github/actions/pytest-action
-      #   with:
-      #     testfile: ./.github/test/test_acapruntimetest.py
-      # - name: Push test image
-      #   # always push the image so that it can be used for debugging if tests fail
-      #   if: success() || failure()
-      #   uses: ./.github/actions/docker-build-push-action
-      #   with:
-      #     dockerfile: Dockerfile.${{ matrix.arch }}
-      #     tags: ${{ steps.meta_test.outputs.tags }}
-      #     labels: ${{ steps.meta_test.outputs.labels }}
-      #     push: true
-      #     build-args: TEST=true
-      #     registry_user: ${{ secrets.DOCKER_HUB_USERNAME }}
-      #     registry_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+      - name: Set environment variables for test
+        shell: bash
+        run: |
+          if [ ${{ matrix.arch }} = armv7hf ]
+          then
+            echo "AXIS_TARGET_ADDR=${{ env.AXIS_TARGET_ADDR_ARMV7HF }}" >> $GITHUB_ENV
+          else
+            echo "AXIS_TARGET_ADDR=${{ env.AXIS_TARGET_ADDR_AARCH64 }}" >> $GITHUB_ENV
+          fi
+          echo "ACAP_DOCKER_IMAGE_NAME=${{ steps.meta_test.outputs.tags }}" >> $GITHUB_ENV
+      - name: Run the test image
+        uses: ./.github/actions/pytest-action
+        with:
+          testfile: ./.github/test/test_acapruntimetest.py
+      - name: Push test image
+        # always push the image so that it can be used for debugging if tests fail
+        if: success() || failure()
+        uses: ./.github/actions/docker-build-push-action
+        with:
+          dockerfile: Dockerfile.${{ matrix.arch }}
+          tags: ${{ steps.meta_test.outputs.tags }}
+          labels: ${{ steps.meta_test.outputs.labels }}
+          push: true
+          build-args: TEST=true
+          registry_user: ${{ env.DOCKER_HUB_USER }}
+          registry_token: ${{ env.DOCKER_HUB_TOKEN }}
 
   # Build base and containerized images and push to Docker Hub
   # Skip this step if not on main branch and if build_and_test job is not successful
-  # build_and_push:
-  #   name: Build and push image(s)
-  #   runs-on: ubuntu-latest
-  #   needs: build_and_test
-  #   if: (github.event_name != 'pull_request')
-  #   strategy:
-  #     matrix:
-  #       arch: [armv7hf, aarch64]
-  #   steps:
-  #     - name: Checkout repo
-  #       # sha for actions/checkout@v3 at time of commit.
-  #       uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
-  #     - name: Create base image metadata
-  #       id: meta
-  #       uses: ./.github/actions/metadata-action
-  #       with:
-  #         suffix: -${{ matrix.arch }}
-  #         repository: ${{ env.DOCKERHUB_REPOSITORY }}
-  #         get_version: 'true'
-  #     - name: Build and push base image
-  #       uses: ./.github/actions/docker-build-push-action
-  #       with:
-  #         dockerfile: Dockerfile.${{ matrix.arch }}
-  #         tags: ${{ steps.meta.outputs.tags }}
-  #         labels: ${{ steps.meta.outputs.labels }}
-  #         push: true
-  #         registry_user: ${{ secrets.DOCKER_HUB_USERNAME }}
-  #         registry_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-  #     - name: Create containerized image metadata
-  #       id: meta_containerized
-  #       uses: ./.github/actions/metadata-action
-  #       with:
-  #         suffix: -${{ matrix.arch }}-containerized
-  #         repository: ${{ env.DOCKERHUB_REPOSITORY }}
-  #     - name: Build and push containerized image
-  #       uses: ./.github/actions/docker-build-push-action
-  #       with:
-  #         dockerfile: Dockerfile.${{ matrix.arch }}-containerized
-  #         tags: ${{ steps.meta_containerized.outputs.tags }}
-  #         labels: ${{ steps.meta_containerized.outputs.labels }}
-  #         push: true
-  #         build-args: |
-  #             ARCH=${{ matrix.arch }}
-  #             RUNTIME_VERSION=${{ steps.meta.outputs.version }}
-  #         use_qemu: 'true'
-  #         registry_user: ${{ secrets.DOCKER_HUB_USERNAME }}
-  #         registry_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+  build_and_push:
+    name: Build and push image(s)
+    runs-on: ubuntu-latest
+    needs: build_and_test
+    if: (github.event_name != 'pull_request')
+    strategy:
+      matrix:
+        arch: [armv7hf, aarch64]
+    steps:
+      - name: Checkout repo
+        # sha for actions/checkout@v3 at time of commit.
+        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
+      - name: Create base image metadata
+        id: meta
+        uses: ./.github/actions/metadata-action
+        with:
+          suffix: -${{ matrix.arch }}
+          repository: ${{ env.DOCKER_HUB_REPOSITORY }}
+          get_version: 'true'
+      - name: Build and push base image
+        uses: ./.github/actions/docker-build-push-action
+        with:
+          dockerfile: Dockerfile.${{ matrix.arch }}
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          push: true
+          registry_user: ${{ env.DOCKER_HUB_USER }}
+          registry_token: ${{ env.DOCKER_HUB_TOKEN }}
+      - name: Create containerized image metadata
+        id: meta_containerized
+        uses: ./.github/actions/metadata-action
+        with:
+          suffix: -${{ matrix.arch }}-containerized
+          repository: ${{ env.DOCKER_HUB_REPOSITORY }}
+      - name: Build and push containerized image
+        uses: ./.github/actions/docker-build-push-action
+        with:
+          dockerfile: Dockerfile.${{ matrix.arch }}-containerized
+          tags: ${{ steps.meta_containerized.outputs.tags }}
+          labels: ${{ steps.meta_containerized.outputs.labels }}
+          push: true
+          build-args: |
+              ARCH=${{ matrix.arch }}
+              RUNTIME_VERSION=${{ steps.meta.outputs.version }}
+          use_qemu: 'true'
+          registry_user: ${{ env.DOCKER_HUB_USER }}
+          registry_token: ${{ env.DOCKER_HUB_TOKEN }}
