linter fixes

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,28 +1,59 @@
-name: Lint codebase
+name: Lint Code Base
 
 on:
-  push:
-  pull_request:
   workflow_dispatch:
+#  push:
+#    branches:
+#      - 'main'
+#  pull_request:
+#    branches:
+#      - '**'
 
 jobs:
-  lint:
+  build:
+    name: Lint Code Base
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout Code
+        uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - uses: github/super-linter/slim@v4
+
+      - name: Lint Code Base
+        uses: github/super-linter/slim@v4
         env:
           VALIDATE_ALL_CODEBASE: true
           DEFAULT_BRANCH: main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          LINTER_RULES_PATH: /
-          MARKDOWN_CONFIG_FILE: .markdownlint.yml
-          DOCKERFILE_HADOLINT_FILE_NAME: .hado-lint.yml
-          YAML_CONFIG_FILE: .yaml-lint.yml
+          IGNORE_GITIGNORED_FILES: true
           VALIDATE_BASH: true
           VALIDATE_DOCKERFILE_HADOLINT: true
           VALIDATE_MARKDOWN: true
           VALIDATE_SHELL_SHFMT: true
           VALIDATE_YAML: true
+
+      - name: Check that linter symbolic links exist in top directory
+        run: |
+          missing_symlinks=""
+          symlinks="\
+            .hadolint.yml \
+            .markdownlint.yml \
+            .yamllint.yml \
+          "
+
+          for syml in $symlinks
+          do
+            [ -L $syml ] && [ -f $syml ] || {
+              missing_symlinks="$syml $missing_symlinks"
+            }
+          done
+
+          [ -z "$missing_symlinks" ] || {
+            echo "ERROR: Missing linter symlinks"
+            echo "The following symlinks are missing in top directory"
+            for msyml in $missing_symlinks
+            do
+              echo "* $msyml"
+            done
+            exit 1
+          }
